---
# Default deployment directory for Neurapress Docker stack
neurapress_deploy_dir: /opt/neurapress
neurapress_workspace: "{{ neurapress_deploy_dir }}"
neurapress_domain: write.svc.plus
neurapress_image: neurapress:prod
neurapress_certbot_email: manbuzhe2009@qq.com
