- name: setup neurapress
  hosts: all
  become: true
  vars:
    neurapress_domain: "{{ domain }}"
    neurapress_workspace: /opt/neurapress
    neurapress_image: neurapress:prod
    neurapress_certbot_email: manbuzhe2009@qq.com
  roles:
    - vhosts/docker/
    - docker/neurapress/
